#!/usr/bin/env bash
set -euo pipefail

echo "Updating openssl..."
yes | sudo apt install openssl > /dev/null

echo "Please insert the password:"
read -s pass

mkdir -p ~/.ssh

cat /assets/.secrets/token_private.txt \
  | dot sec decrypt -p "$pass" \
  > /assets/.ssh/id_rsa

cat /assets/.secrets/token_public.txt \
  | dot sec decrypt -p "$pass" \
  > ~/.ssh/id_rsa.pub

ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa; git clone git@github.com:denisidoro/klapaucius.git'
