#!/usr/bin/env bash
set -euo pipefail

export DOTFILES="${HOME}/.dotfiles"

install_dotfiles() {
  git clone https://github.com/denisidoro/dotfiles "$DOTFILES"
  cd "$DOTFILES"
  "${DOTFILES}/bin/dot" self install default
}

echo "apt updating..."
apt update > /dev/null || true

echo
echo "Installing dotfiles..."
install_dotfiles > /dev/null
